[workspace]
name = "mcsolverengine"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
eigen = ">=3.3,<5"
libboost-devel = "*"
occt = ">=7.8,<7.9"

[tool.pixi.pypi-dependencies]
rhino3dm = "*"
