[workspace]
name = "mcsolverengine"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
eigen = "3.4.0"
libboost-devel = "1.84.0"
occt = "7.8.1"

[tool.pixi.pypi-dependencies]
rhino3dm = "*"
